### ISSUE TITLE
What if the same shared_pointer is passed again? 

### ISSUE THREAD

**Issue by jain14aditya** [manishmanu/comp_coding_algos#2]
https://github.com/manishmanu/comp_coding_algos/blob/ad3c76269dcd7c6ddb493b79793f0c504315d31f/cpp/my_shared_ptr.cc#L28

**Comment by manishmanu** [comment]
Resolved. `commit id`: [401e785a72ea74858001637b7af32ff23d2b3ed6](https://github.com/manishmanu/comp_coding_algos/commit/401e785a72ea74858001637b7af32ff23d2b3ed6)
